### PR TITLE
Add updated pacman(-mirror) packages that use a git-for-windows mirrorli...

### PR DESCRIPTION
**Pull request by sschuberth**
...st

This removes the old pacman-4.2.0.6082.e76619f-1 for which we never had a
x86_64 version.

Signed-off-by: Sebastian Schuberth sebastian.schuberth@here.com

### CODE REVIEW

**Comment by sschuberth** [comment]
These are the binaries for https://github.com/git-for-windows/MSYS2-packages/pull/9.

**Comment by dscho** [comment]
Thanks!

**Comment by sschuberth** [comment]
Uhm, wait a second. How comes you're fine with this, if according to our discussion at https://github.com/git-for-windows/git/issues/30 you're not fine what the associated source code at https://github.com/git-for-windows/MSYS2-packages/pull/9 does?

**Comment by dscho** [comment]
This is just a workaround to move existing users to our Bintray repositories, yes?

**Comment by sschuberth** [comment]
I would not call it a "workaround", but yes, I simply would like to have a "switch" point in time for which the GitHub and Bintray repos contain the same packages, verify that Bintray works, from then on only update the Bintray repo, and eventually delete the GitHub one.

**Pull request merged**
